import namespace from 'helpers/namespace';

export default namespace(
  {
    PAGE_READY: null,

    INIT_UPDATE_CONNECTION: null,
    INIT_UPDATE_DETAILS: null,
    INIT_UPDATE_EMAIL: null,

    GET_STORE_DETAILS_REQUEST: null,
    GET_STORE_DETAILS_SUCCESS: null,
    GET_STORE_DETAILS_FAILURE: null,

    GET_GENERAL_DETAILS_REQUEST: null,
    GET_GENERAL_DETAILS_SUCCESS: null,
    GET_GENERAL_DETAILS_FAILURE: null,

    UPDATE_GENERAL_DETAILS_REQUEST: null,
    UPDATE_GENERAL_DETAILS_SUCCESS: null,
    UPDATE_GENERAL_DETAILS_FAILURE: null,

    SET_EMAIL_REQUEST: null,
    SET_EMAIL_SUCCESS: null,
    SET_EMAIL_FAILURE: null,

    UPDATE_TEAM_REQUEST: null,
    UPDATE_TEAM_SUCCESS: null,
    UPDATE_TEAM_FAILURE: null,

    GET_TEAM_REQUEST: null,
    GET_TEAM_SUCCESS: null,
    GET_TEAM_FAILURE: null,

    UPDATE_NOTIFICATIONS_REQUEST: null,
    UPDATE_NOTIFICATIONS_SUCCESS: null,
    UPDATE_NOTIFICATIONS_FAILURE: null,

    GET_NOTIFICATIONS_REQUEST: null,
    GET_NOTIFICATIONS_SUCCESS: null,
    GET_NOTIFICATIONS_FAILURE: null,

    UPDATE_STORE_DETAILS_REQUEST: null,
    UPDATE_STORE_DETAILS_SUCCESS: null,
    UPDATE_STORE_DETAILS_FAILURE: null,
  },
  'SETTINGS'
);
