import namespace from 'helpers/namespace';

export default namespace(
  {
    POST_GOOGLE_ADS_CONNECT_REQUEST: null,
    POST_GOOGLE_ADS_CONNECT_SUCCESS: null,
    POST_GOOGLE_ADS_CONNECT_FAILURE: null,

    POST_GOOGLE_ANALYTICS_CONNECT_REQUEST: null,
    POST_GOOGLE_ANALYTICS_CONNECT_SUCCESS: null,
    POST_GOOGLE_ANALYTICS_CONNECT_FAILURE: null,

    POST_SHOPIFY_CONNECT_REQUEST: null,
    POST_SHOPIFY_CONNECT_SUCCESS: null,
    POST_SHOPIFY_CONNECT_FAILURE: null,

    POST_FACEBOOK_CONNECT_REQUEST: null,
    POST_FACEBOOK_CONNECT_SUCCESS: null,
    POST_FACEBOOK_CONNECT_FAILURE: null,

    POST_INSTAGRAM_CONNECT_REQUEST: null,
    POST_INSTAGRAM_CONNECT_SUCCESS: null,
    POST_INSTAGRAM_CONNECT_FAILURE: null,

    GET_ALL_CONNECTIONS_REQUEST: null,
    GET_ALL_CONNECTIONS_SUCCESS: null,
    GET_ALL_CONNECTIONS_FAILURE: null,

    INIT_SHOPIFY_INTEGRATION: null,
    INIT_GA_INTEGRATION: null,
    INIT_G_ADS_INTEGRATION: null,

    SET_ORGANIZATION_REQUEST: null,
    SET_ORGANIZATION_SUCCESS: null,
    SET_ORGANIZATION_FAILURE: null,
  },
  'CONNECTIONS'
);
