import namespace from 'helpers/namespace';

export default namespace(
  {
    GET_AUDIT_STEP_REQUEST: null,
    GET_AUDIT_STEP_SUCCESS: null,
    GET_AUDIT_STEP_FAILURE: null,

    GET_AUDIT_RUN_REQUEST: null,
    GET_AUDIT_RUN_SUCCESS: null,
    GET_AUDIT_RUN_FAILURE: null,

    GET_AUDIT_STATUS_REQUEST: null,
    GET_AUDIT_STATUS_SUCCESS: null,
    GET_AUDIT_STATUS_FAILURE: null,

    GET_ANALYTICS_ACCOUNTS_REQUEST: null,
    GET_ANALYTICS_ACCOUNTS_SUCCESS: null,
    GET_ANALYTICS_ACCOUNTS_FAILURE: null,

    GET_ACCOUNT_PROPERTIES_REQUEST: null,
    GET_ACCOUNT_PROPERTIES_SUCCESS: null,
    GET_ACCOUNT_PROPERTIES_FAILURE: null,

    GET_ACCOUNT_VIEWS_REQUEST: null,
    GET_ACCOUNT_VIEWS_SUCCESS: null,
    GET_ACCOUNT_VIEWS_FAILURE: null,
  },
  'AUDIT'
);
